# Generated by Django 3.1.2 on 2020-10-29 22:03

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201030_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'ArticleCamment', 'verbose_name_plural': 'ArticleCamments'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.FloatField(blank=True, null=True, verbose_name=article.models.Categotry),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='article.Tag'),
        ),
    ]
