# Generated by Django 3.1.2 on 2020-11-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201102_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_time',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='update_time',
            new_name='update_date',
        ),
    ]
